window.manifestData = [
    {
        "insurer":  "Allianz",
        "documentType":  "AuditReport",
        "employeeId":  "EMP009",
        "employeeName":  "Lukasz Maj",
        "documentFilename":  "20250913-AuditReport-EMP009.pdf",
        "receivedAt":  "2025-09-13T23:57:02.3847606+03:00",
        "signatureRequirement":  "QES",
        "deliveryChannel":  "API",
        "deliveryTarget":  "https://sandbox.allianz.example/api/audit-report",
        "status":  "pending",
        "notes":  "Contains all required annexes for AuditReport."
    },
    {
        "insurer":  "Allianz",
        "documentType":  "AuditReport",
        "employeeId":  "EMP011",
        "employeeName":  "Bartosz Wisniewski",
        "documentFilename":  "20250908-AuditReport-EMP011.pdf",
        "receivedAt":  "2025-09-08T20:18:02.3847606+03:00",
        "signatureRequirement":  "QES",
        "deliveryChannel":  "API",
        "deliveryTarget":  "https://sandbox.allianz.example/api/audit-report",
        "status":  "pending",
        "notes":  "Awaiting TrustLynx signature guidance for AuditReport."
    },
    {
        "insurer":  "Allianz",
        "documentType":  "ClaimForm",
        "employeeId":  "EMP010",
        "employeeName":  "Tomasz Falkowski",
        "documentFilename":  "20250905-ClaimForm-EMP010.pdf",
        "receivedAt":  "2025-09-06T09:50:02.3847606+03:00",
        "signatureRequirement":  "QES",
        "deliveryChannel":  "Email",
        "deliveryTarget":  "claim-form@allianz-sandbox.example.com",
        "status":  "pending",
        "notes":  "Contains all required annexes for ClaimForm."
    },
    {
        "insurer":  "Allianz",
        "documentType":  "ComplianceCertificate",
        "employeeId":  "EMP003",
        "employeeName":  "Xavier Ratajczak",
        "documentFilename":  "20250901-ComplianceCertificate-EMP003.pdf",
        "receivedAt":  "2025-09-01T19:06:02.3847606+03:00",
        "signatureRequirement":  "QES",
        "deliveryChannel":  "API",
        "deliveryTarget":  "https://sandbox.allianz.example/api/compliance-cert",
        "status":  "pending",
        "notes":  "Auto-generated ComplianceCertificate package for quarterly review."
    },
    {
        "insurer":  "Allianz",
        "documentType":  "ComplianceCertificate",
        "employeeId":  "EMP013",
        "employeeName":  "Norbert Sawicki",
        "documentFilename":  "20250901-ComplianceCertificate-EMP013.pdf",
        "receivedAt":  "2025-09-01T22:42:02.3847606+03:00",
        "signatureRequirement":  "QES",
        "deliveryChannel":  "API",
        "deliveryTarget":  "https://sandbox.allianz.example/api/compliance-cert",
        "status":  "pending",
        "notes":  "Ready for single-click batch pipeline (ComplianceCertificate)."
    },
    {
        "insurer":  "Allianz",
        "documentType":  "ComplianceCertificate",
        "employeeId":  "EMP020",
        "employeeName":  "Iwona Lis",
        "documentFilename":  "20250905-ComplianceCertificate-EMP020.pdf",
        "receivedAt":  "2025-09-06T03:30:02.3847606+03:00",
        "signatureRequirement":  "QES",
        "deliveryChannel":  "Email",
        "deliveryTarget":  "compliance-cert@allianz-sandbox.example.com",
        "status":  "pending",
        "notes":  "Auto-generated ComplianceCertificate package for quarterly review."
    },
    {
        "insurer":  "Allianz",
        "documentType":  "Onboarding",
        "employeeId":  "EMP022",
        "employeeName":  "Gosia Mazurek",
        "documentFilename":  "20250911-Onboarding-EMP022.pdf",
        "receivedAt":  "2025-09-12T05:53:02.3847606+03:00",
        "signatureRequirement":  "QES",
        "deliveryChannel":  "Email",
        "deliveryTarget":  "onboarding@allianz-sandbox.example.com",
        "status":  "pending",
        "notes":  "Includes supplemental exhibits for Onboarding."
    },
    {
        "insurer":  "Allianz",
        "documentType":  "Onboarding",
        "employeeId":  "EMP025",
        "employeeName":  "Bartosz Zielinska",
        "documentFilename":  "20250902-Onboarding-EMP025.pdf",
        "receivedAt":  "2025-09-02T17:55:02.3847606+03:00",
        "signatureRequirement":  "QES",
        "deliveryChannel":  "Email",
        "deliveryTarget":  "onboarding@allianz-sandbox.example.com",
        "status":  "pending",
        "notes":  "Auto-generated Onboarding package for quarterly review."
    },
    {
        "insurer":  "Allianz",
        "documentType":  "PolicyRenewal",
        "employeeId":  "EMP021",
        "employeeName":  "Rafal Piatek",
        "documentFilename":  "20250919-PolicyRenewal-EMP021.pdf",
        "receivedAt":  "2025-09-19T22:52:02.3847606+03:00",
        "signatureRequirement":  "QES",
        "deliveryChannel":  "API",
        "deliveryTarget":  "https://sandbox.allianz.example/api/policy-renewal",
        "status":  "pending",
        "notes":  "Includes supplemental exhibits for PolicyRenewal."
    },
    {
        "insurer":  "Generali",
        "documentType":  "AuditReport",
        "employeeId":  "EMP002",
        "employeeName":  "Urszula Janik",
        "documentFilename":  "20250907-AuditReport-EMP002.pdf",
        "receivedAt":  "2025-09-07T18:54:02.3847606+03:00",
        "signatureRequirement":  "AES",
        "deliveryChannel":  "Email",
        "deliveryTarget":  "audit-report@generali-sandbox.example.com",
        "status":  "pending",
        "notes":  "Contains all required annexes for AuditReport."
    },
    {
        "insurer":  "Generali",
        "documentType":  "AuditReport",
        "employeeId":  "EMP019",
        "employeeName":  "Gosia Lis",
        "documentFilename":  "20250918-AuditReport-EMP019.pdf",
        "receivedAt":  "2025-09-18T17:45:02.3847606+03:00",
        "signatureRequirement":  "AES",
        "deliveryChannel":  "API",
        "deliveryTarget":  "https://sandbox.generali.example/api/audit-report",
        "status":  "pending",
        "notes":  "Includes supplemental exhibits for AuditReport."
    },
    {
        "insurer":  "Generali",
        "documentType":  "ClaimForm",
        "employeeId":  "EMP001",
        "employeeName":  "Hubert Ratajczak",
        "documentFilename":  "20250831-ClaimForm-EMP001.pdf",
        "receivedAt":  "2025-08-31T20:36:02.3847606+03:00",
        "signatureRequirement":  "AES",
        "deliveryChannel":  "Email",
        "deliveryTarget":  "claim-form@generali-sandbox.example.com",
        "status":  "pending",
        "notes":  "Includes supplemental exhibits for ClaimForm."
    },
    {
        "insurer":  "Generali",
        "documentType":  "ClaimForm",
        "employeeId":  "EMP016",
        "employeeName":  "Yvonne Król",
        "documentFilename":  "20250831-ClaimForm-EMP016.pdf",
        "receivedAt":  "2025-09-01T02:44:02.3847606+03:00",
        "signatureRequirement":  "AES",
        "deliveryChannel":  "API",
        "deliveryTarget":  "https://sandbox.generali.example/api/claim-form",
        "status":  "pending",
        "notes":  "Awaiting TrustLynx signature guidance for ClaimForm."
    },
    {
        "insurer":  "Generali",
        "documentType":  "ClaimForm",
        "employeeId":  "EMP030",
        "employeeName":  "Yvonne Urban",
        "documentFilename":  "20250920-ClaimForm-EMP030.pdf",
        "receivedAt":  "2025-09-21T02:41:02.3847606+03:00",
        "signatureRequirement":  "AES",
        "deliveryChannel":  "API",
        "deliveryTarget":  "https://sandbox.generali.example/api/claim-form",
        "status":  "pending",
        "notes":  "Ready for single-click batch pipeline (ClaimForm)."
    },
    {
        "insurer":  "Generali",
        "documentType":  "Onboarding",
        "employeeId":  "EMP026",
        "employeeName":  "Olga Kowalski",
        "documentFilename":  "20250915-Onboarding-EMP026.pdf",
        "receivedAt":  "2025-09-16T01:05:02.3847606+03:00",
        "signatureRequirement":  "AES",
        "deliveryChannel":  "Email",
        "deliveryTarget":  "onboarding@generali-sandbox.example.com",
        "status":  "pending",
        "notes":  "Auto-generated Onboarding package for quarterly review."
    },
    {
        "insurer":  "LINK4",
        "documentType":  "AuditReport",
        "employeeId":  "EMP012",
        "employeeName":  "Marta Wisniewski",
        "documentFilename":  "20250905-AuditReport-EMP012.pdf",
        "receivedAt":  "2025-09-06T06:14:02.3847606+03:00",
        "signatureRequirement":  "QES",
        "deliveryChannel":  "Email",
        "deliveryTarget":  "audit-report@link4-sandbox.example.com",
        "status":  "pending",
        "notes":  "Prepared for expedited insurer validation (AuditReport)."
    },
    {
        "insurer":  "LINK4",
        "documentType":  "PolicyRenewal",
        "employeeId":  "EMP014",
        "employeeName":  "Marta Urban",
        "documentFilename":  "20250914-PolicyRenewal-EMP014.pdf",
        "receivedAt":  "2025-09-14T21:01:02.3847606+03:00",
        "signatureRequirement":  "QES",
        "deliveryChannel":  "Email",
        "deliveryTarget":  "policy-renewal@link4-sandbox.example.com",
        "status":  "pending",
        "notes":  "Prepared for expedited insurer validation (PolicyRenewal)."
    },
    {
        "insurer":  "Nationale",
        "documentType":  "AuditReport",
        "employeeId":  "EMP017",
        "employeeName":  "Urszula Lewandowski",
        "documentFilename":  "20250920-AuditReport-EMP017.pdf",
        "receivedAt":  "2025-09-21T02:02:02.3847606+03:00",
        "signatureRequirement":  "AES",
        "deliveryChannel":  "Email",
        "deliveryTarget":  "audit-report@nationale-sandbox.example.com",
        "status":  "pending",
        "notes":  "Contains all required annexes for AuditReport."
    },
    {
        "insurer":  "Nationale",
        "documentType":  "AuditReport",
        "employeeId":  "EMP023",
        "employeeName":  "Zofia Falkowski",
        "documentFilename":  "20250919-AuditReport-EMP023.pdf",
        "receivedAt":  "2025-09-20T03:11:02.3847606+03:00",
        "signatureRequirement":  "AES",
        "deliveryChannel":  "API",
        "deliveryTarget":  "https://sandbox.nationale.example/api/audit-report",
        "status":  "pending",
        "notes":  "Contains all required annexes for AuditReport."
    },
    {
        "insurer":  "Nationale",
        "documentType":  "CoverageUpdate",
        "employeeId":  "EMP028",
        "employeeName":  "Hubert Czarnecki",
        "documentFilename":  "20250829-CoverageUpdate-EMP028.pdf",
        "receivedAt":  "2025-08-29T18:06:02.3847606+03:00",
        "signatureRequirement":  "AES",
        "deliveryChannel":  "Email",
        "deliveryTarget":  "coverage-update@nationale-sandbox.example.com",
        "status":  "pending",
        "notes":  "Contains all required annexes for CoverageUpdate."
    },
    {
        "insurer":  "Nationale",
        "documentType":  "PolicyRenewal",
        "employeeId":  "EMP004",
        "employeeName":  "Piotr Wrobel",
        "documentFilename":  "20250904-PolicyRenewal-EMP004.pdf",
        "receivedAt":  "2025-09-04T13:20:02.3847606+03:00",
        "signatureRequirement":  "AES",
        "deliveryChannel":  "Email",
        "deliveryTarget":  "policy-renewal@nationale-sandbox.example.com",
        "status":  "pending",
        "notes":  "Contains all required annexes for PolicyRenewal."
    },
    {
        "insurer":  "Nationale",
        "documentType":  "PolicyRenewal",
        "employeeId":  "EMP007",
        "employeeName":  "Norbert Sikorska",
        "documentFilename":  "20250831-PolicyRenewal-EMP007.pdf",
        "receivedAt":  "2025-09-01T11:55:02.3847606+03:00",
        "signatureRequirement":  "AES",
        "deliveryChannel":  "Email",
        "deliveryTarget":  "policy-renewal@nationale-sandbox.example.com",
        "status":  "pending",
        "notes":  "Prepared for expedited insurer validation (PolicyRenewal)."
    },
    {
        "insurer":  "Nationale",
        "documentType":  "PolicyRenewal",
        "employeeId":  "EMP015",
        "employeeName":  "Tomasz Osinski",
        "documentFilename":  "20250918-PolicyRenewal-EMP015.pdf",
        "receivedAt":  "2025-09-19T02:01:02.3847606+03:00",
        "signatureRequirement":  "AES",
        "deliveryChannel":  "API",
        "deliveryTarget":  "https://sandbox.nationale.example/api/policy-renewal",
        "status":  "pending",
        "notes":  "Ready for single-click batch pipeline (PolicyRenewal)."
    },
    {
        "insurer":  "Nationale",
        "documentType":  "PolicyRenewal",
        "employeeId":  "EMP024",
        "employeeName":  "Alice Kowalski",
        "documentFilename":  "20250911-PolicyRenewal-EMP024.pdf",
        "receivedAt":  "2025-09-11T20:51:02.3847606+03:00",
        "signatureRequirement":  "AES",
        "deliveryChannel":  "Email",
        "deliveryTarget":  "policy-renewal@nationale-sandbox.example.com",
        "status":  "pending",
        "notes":  "Awaiting TrustLynx signature guidance for PolicyRenewal."
    },
    {
        "insurer":  "PZU",
        "documentType":  "ClaimForm",
        "employeeId":  "EMP029",
        "employeeName":  "Ewa Sawicki",
        "documentFilename":  "20250919-ClaimForm-EMP029.pdf",
        "receivedAt":  "2025-09-19T14:16:02.3847606+03:00",
        "signatureRequirement":  "QES",
        "deliveryChannel":  "API",
        "deliveryTarget":  "https://sandbox.pzu.example/api/claim-form",
        "status":  "pending",
        "notes":  "Ready for single-click batch pipeline (ClaimForm)."
    },
    {
        "insurer":  "PZU",
        "documentType":  "ComplianceCertificate",
        "employeeId":  "EMP027",
        "employeeName":  "Gosia Lewandowski",
        "documentFilename":  "20250909-ComplianceCertificate-EMP027.pdf",
        "receivedAt":  "2025-09-09T23:43:02.3847606+03:00",
        "signatureRequirement":  "QES",
        "deliveryChannel":  "API",
        "deliveryTarget":  "https://sandbox.pzu.example/api/compliance-cert",
        "status":  "pending",
        "notes":  "Awaiting TrustLynx signature guidance for ComplianceCertificate."
    },
    {
        "insurer":  "PZU",
        "documentType":  "CoverageUpdate",
        "employeeId":  "EMP006",
        "employeeName":  "Sylwia Urban",
        "documentFilename":  "20250831-CoverageUpdate-EMP006.pdf",
        "receivedAt":  "2025-09-01T10:32:02.3847606+03:00",
        "signatureRequirement":  "QES",
        "deliveryChannel":  "Email",
        "deliveryTarget":  "coverage-update@pzu-sandbox.example.com",
        "status":  "pending",
        "notes":  "Auto-generated CoverageUpdate package for quarterly review."
    },
    {
        "insurer":  "PZU",
        "documentType":  "Onboarding",
        "employeeId":  "EMP008",
        "employeeName":  "Olga Lewandowski",
        "documentFilename":  "20250909-Onboarding-EMP008.pdf",
        "receivedAt":  "2025-09-09T21:08:02.3847606+03:00",
        "signatureRequirement":  "QES",
        "deliveryChannel":  "API",
        "deliveryTarget":  "https://sandbox.pzu.example/api/onboarding",
        "status":  "pending",
        "notes":  "Prepared for expedited insurer validation (Onboarding)."
    },
    {
        "insurer":  "PZU",
        "documentType":  "PolicyRenewal",
        "employeeId":  "EMP005",
        "employeeName":  "Sylwia Osinski",
        "documentFilename":  "20250917-PolicyRenewal-EMP005.pdf",
        "receivedAt":  "2025-09-18T03:32:02.3847606+03:00",
        "signatureRequirement":  "QES",
        "deliveryChannel":  "Email",
        "deliveryTarget":  "policy-renewal@pzu-sandbox.example.com",
        "status":  "pending",
        "notes":  "Contains all required annexes for PolicyRenewal."
    },
    {
        "insurer":  "PZU",
        "documentType":  "PolicyRenewal",
        "employeeId":  "EMP018",
        "employeeName":  "Damian Lewandowski",
        "documentFilename":  "20250924-PolicyRenewal-EMP018.pdf",
        "receivedAt":  "2025-09-24T18:29:02.3847606+03:00",
        "signatureRequirement":  "QES",
        "deliveryChannel":  "API",
        "deliveryTarget":  "https://sandbox.pzu.example/api/policy-renewal",
        "status":  "pending",
        "notes":  "Auto-generated PolicyRenewal package for quarterly review."
    }
];

